version: 2.1
jobs:
  test:
    docker:
    - image: 'cypress/included:12.6.0'
    steps:
    - checkout
    - run: npm install
    - run: npm install -g gulp
    - run:
        name: Build application
        command: gulp
        background: true
    - run: npx cypress run
workflows:
  build:
    jobs:
    - test

